//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int product_id { get; set; }
        public string product_articule { get; set; }
        public string product_name { get; set; }
        public string product_unit { get; set; }
        public Nullable<int> product_price { get; set; }
        public Nullable<int> product_max_discount { get; set; }
        public string product_maker { get; set; }
        public string product_provider { get; set; }
        public string product_category { get; set; }
        public Nullable<int> product_discount { get; set; }
        public Nullable<int> product_count { get; set; }
        public string product_description { get; set; }
        public string product_img_url { get; set; }
    }
}
